<?php $count = $this->getNotificationCount(); ?>
<?php if($count > 0) { ?>
    <p class="rep-notification overdue-notification">You have <?php echo $count ?> unread notifications. <a href="<?php echo $this->getNotificationUrl() ?>">Click Here</a> to view.</p>
    <style>
        .rep-notification {
            color: #ff0000;
            padding: 5px 20px;
            font-weight: bold;
            font-size: 14px;
            text-align: center;
        }
    </style>
<?php } ?>