<script>
  jQuery(document).ready(function($){
      var divs = $('.header-ad');

      function fade() {
          var current = $('#header-top-ad .current');
          var currentIndex = divs.index(current),
              nextIndex = currentIndex + 1;
          if (nextIndex >= divs.length) {
              nextIndex = 0;
          }
          var next = divs.eq(nextIndex);
          next.stop().fadeIn(1000, function () {
              $(this).addClass('current');
          });
          current.stop().fadeOut(1000, function () {
              $(this).removeClass('current');
              setTimeout(fade, 4000);
          });
      }
      setTimeout(fade, 4000);
  });
</script>

<?php if(Mage::getStoreConfig('widget_setup/openpayconfig/openpay_enable',Mage::app()->getStore())){ ?>

<div id="header-top-ad">

<?php
$logo1 = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'openpaywidget/logo.png';
$logo2 = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'openpaywidget/logo.png';
$logo3 = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'openpaywidget/logo.png';

if(Mage::getStoreConfig('widget_setup/popupwidget/openpay_logo_1',Mage::app()->getStore())){
  $logo1 = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product/watermark/'.Mage::getStoreConfig('widget_setup/popupwidget/openpay_logo_1',Mage::app()->getStore());
}
if(Mage::getStoreConfig('widget_setup/popupwidget/openpay_logo_2',Mage::app()->getStore())){
  $logo2 = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product/watermark/'.Mage::getStoreConfig('widget_setup/popupwidget/openpay_logo_2',Mage::app()->getStore());
}
if(Mage::getStoreConfig('widget_setup/popupwidget/openpay_logo_3',Mage::app()->getStore())){
  $logo3 = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'catalog/product/watermark/'.Mage::getStoreConfig('widget_setup/popupwidget/openpay_logo_3',Mage::app()->getStore());
}
?>
<?php
if(Mage::getStoreConfig('widget_setup/popupwidget/openpay_popup1_enable',Mage::app()->getStore())==1){ ?>
    <div class="header-ad current" style="background: #<?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_colour_1',Mage::app()->getStore()); ?>">
        <div class="container">
          <div class="content-text"><div class="text-wrapper">
            <img src="<?php echo $logo1; ?>" height="18" />
            <span style="color: #<?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_font_colour_1',Mage::app()->getStore()); ?>;"> <?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_text_1',Mage::app()->getStore()); ?> <a  style="color: #<?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_font_colour_1',Mage::app()->getStore()); ?>;" href="javascript:void(0);" class="openpay-modal-view" data-toggle="modal" data-target="#myModal" >Learn more</a></span></div>
          </div>
        </div>
    </div>
<?php }if(Mage::getStoreConfig('widget_setup/popupwidget/openpay_popup2_enable',Mage::app()->getStore())==1){ ?>
    <div class="header-ad" style="background-color: #<?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_colour_2',Mage::app()->getStore()); ?>">
        <div class="container">
          <div class="content-text"><div class="text-wrapper">
            <img src="<?php echo $logo2; ?>" height="18" />
            <span style="color: #<?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_font_colour_2',Mage::app()->getStore()); ?>; "> <?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_text_2',Mage::app()->getStore()); ?> <a style="color: #<?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_font_colour_2',Mage::app()->getStore()); ?>;" href="javascript:void(0);" class="openpay-modal-view" data-toggle="modal" data-target="#myModal1" >Learn more</a></span></div>
          </div>  
        </div>
    </div>
<?php }if(Mage::getStoreConfig('widget_setup/popupwidget/openpay_popup3_enable',Mage::app()->getStore())==1){ ?>
    <div class="header-ad" style="background: #<?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_colour_3',Mage::app()->getStore()); ?>">
        <div class="container">
          <div class="content-text"><div class="text-wrapper">
            <img src="<?php echo $logo3; ?>" height="18" />
            <span style="color: #<?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_font_colour_3',Mage::app()->getStore()); ?>;"> <?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_text_3',Mage::app()->getStore()); ?> <a style="color: #<?php echo Mage::getStoreConfig('widget_setup/popupwidget/popup_font_colour_3',Mage::app()->getStore()); ?>;" href="javascript:void(0);" class="openpay-modal-view" data-toggle="modal" data-target="#myModal2" >Learn more</a></span></div>
          </div>
        </div>
    </div>
<?php }?>
    <!-- Modal -->
    <div class="modal fade" id="myModal" role="dialog">
      <div class="modal-dialog openpay-dialog">
      
        <!-- Modal content-->
        <div class="">
            <div class="main-outer-openpay-modal">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <a class="logo" href="javascript:void(0)"><img src="<?php echo $logo1; ?>" alt=""></a>
              <p>Openpay is a simple and flexible way to buy now <br>and pay later - with zero interest. We offer longer, more flexible terms all easily managed through the Openpay App.</p>
              <div class="main-body">
                <h2>Buy with Openpay in 3 easy steps:</h2>
                <ul class="step-sec">
                  <li>
                    <div class="inner">
                      <div class="step">
                        <div class="step-inner">
                          <span>1</span>
                        </div>
                      </div>
                      <p>Shop &amp; <br>checkout</p>
                    </div>
                  </li>
                  <li>
                    <div class="inner">
                      <div class="step">
                        <div class="step-inner">
                          <span>2</span>
                        </div>
                      </div>
                      <p>Select Openpay from payment options</p>
                    </div>
                  </li>
                  <li>
                    <div class="inner">
                      <div class="step">
                        <div class="step-inner">
                          <span>3</span>
                        </div>
                      </div>
                      <p>Register &amp; design your plan</p>
                    </div>
                  </li>
                </ul>
                <p>If you are 18 years or older and a permanent resident of Australia all you’ll  need is:</p>
                <ul class="enquery">
                  <li>Photo ID</li>
                  <li>Debit or credit card</li>
                  <li>Email address</li>
                  <li>The required deposit</li>
                  <li>Mobile phone (+ another contact number)</li>
                </ul>
              </div>
              <p class="terms">Full terms here</p>
              <p class="copyright">© Openpay 2017</p>
              <p class="site-link">openpay.com.au</p>
              <span class="bottom-left"></span>
            </div>

        </div>
        
      </div>
    </div>

    <!-- Modal 1 -->
    <div class="modal fade" id="myModal1" role="dialog">
      <div class="modal-dialog openpay-dialog">
      
        <!-- Modal content-->
        <div class="">
            <div class="main-outer-openpay-modal">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <a class="logo" href="javascript:void(0)"><img src="<?php echo $logo2; ?>" alt=""></a>
              <p>Openpay is a simple and flexible way to buy now <br>and pay later - with zero interest. We offer longer, more flexible terms all easily managed through the Openpay App.</p>
              <div class="main-body">
                <h2>Buy with Openpay in 3 easy steps:</h2>
                <ul class="step-sec">
                  <li>
                    <div class="inner">
                      <div class="step">
                        <div class="step-inner">
                          <span>1</span>
                        </div>
                      </div>
                      <p>Shop &amp; <br>checkout</p>
                    </div>
                  </li>
                  <li>
                    <div class="inner">
                      <div class="step">
                        <div class="step-inner">
                          <span>2</span>
                        </div>
                      </div>
                      <p>Select Openpay from payment options</p>
                    </div>
                  </li>
                  <li>
                    <div class="inner">
                      <div class="step">
                        <div class="step-inner">
                          <span>3</span>
                        </div>
                      </div>
                      <p>Register &amp; design your plan</p>
                    </div>
                  </li>
                </ul>
                <p>If you are 18 years or older and a permanent resident of Australia all you’ll  need is:</p>
                <ul class="enquery">
                  <li>Photo ID</li>
                  <li>Debit or credit card</li>
                  <li>Email address</li>
                  <li>The required deposit</li>
                  <li>Mobile phone (+ another contact number)</li>
                </ul>
              </div>
              <p class="terms">Full terms here</p>
              <p class="copyright">© Openpay 2017</p>
              <p class="site-link">openpay.com.au</p>
              <span class="bottom-left"></span>
            </div>

        </div>
        
      </div>
    </div>

    <!-- Modal 2-->
    <div class="modal fade" id="myModal2" role="dialog">
      <div class="modal-dialog openpay-dialog">
      
        <!-- Modal content-->
        <div class="">
            <div class="main-outer-openpay-modal">
              <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
              <a class="logo" href="javascript:void(0)"><img src="<?php echo $logo3; ?>" alt=""></a>
              <p>Openpay is a simple and flexible way to buy now <br>and pay later - with zero interest. We offer longer, more flexible terms all easily managed through the Openpay App.</p>
              <div class="main-body">
                <h2>Buy with Openpay in 3 easy steps:</h2>
                <ul class="step-sec">
                  <li>
                    <div class="inner">
                      <div class="step">
                        <div class="step-inner">
                          <span>1</span>
                        </div>
                      </div>
                      <p>Shop &amp; <br>checkout</p>
                    </div>
                  </li>
                  <li>
                    <div class="inner">
                      <div class="step">
                        <div class="step-inner">
                          <span>2</span>
                        </div>
                      </div>
                      <p>Select Openpay from payment options</p>
                    </div>
                  </li>
                  <li>
                    <div class="inner">
                      <div class="step">
                        <div class="step-inner">
                          <span>3</span>
                        </div>
                      </div>
                      <p>Register &amp; design your plan</p>
                    </div>
                  </li>
                </ul>
                <p>If you are 18 years or older and a permanent resident of Australia all you’ll  need is:</p>
                <ul class="enquery">
                  <li>Photo ID</li>
                  <li>Debit or credit card</li>
                  <li>Email address</li>
                  <li>The required deposit</li>
                  <li>Mobile phone (+ another contact number)</li>
                </ul>
              </div>
              <p class="terms">Full terms here</p>
              <p class="copyright">© Openpay 2017</p>
              <p class="site-link">openpay.com.au</p>
              <span class="bottom-left"></span>
            </div>

        </div>
        
      </div>
    </div>
</div>

<?php } ?>