<?php

//$sessionVars = Mage::getSingleton('adminhtml/session')->getSessionVars();
$sessionVars = $block->getAdminSessionModel()->getSessionVars();
$page = ($sessionVars['page']) ? $sessionVars['page'] : 1;
$limit = ($sessionVars['limit']) ? $sessionVars['limit'] : 20;
?>



<div class="entry-edit">
    <h2>Invoices/Purchases</h2>
</div>
<div id="invoicesGrid">
    <input id="total_page" name="total_page" type="hidden" value="<?php echo isset($totalPage) ? $totalPage : '' ?>"/>
    <table cellspacing="0" class="actions custom-pagination">
        <tbody>
            <tr>
                
                <td class="filter-actions a-left custom-pagination-left">
                    <button type="button" class="scalable" id="invoiceResetFilter"><span>Reset Filter</span></button>
                    <button type="button" class="scalable task" id="invoiceDoFilter" ><span>Search</span></button>
                    <button type="button" class="scalable save" id="invoiceUpdate"><span>Submit</span></button>
                </td>
                <td class="pager a-right admin__data-grid-pager-wrap custom-pagination-left"></td>
            </tr>
        </tbody>
    </table>
    <div class="grid">
        <div class="hor-scroll">
            <table cellspacing="0" class="data" id="invoicesGrid_table">
                <colgroup>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead>
                    <tr class="headings">
                        <th><span class="nobr"></span></th>
                        <th><span class="nobr">Order Date</span></th>
                        <th><span class="nobr">Order #</span></th>
                        <th><span class="nobr">Name</span></th>
                        <th><span class="nobr">Qty</span></th>
                        <th><span class="nobr">SKU</span></th>
                        <th><span class="nobr">Items</span></th>
                        <th><span class="nobr">Unit Price</span></th>
                        <th><span class="nobr">Totals</span></th>
                        <th><span class="nobr">Assign to</span></th>
                        <th><span class="nobr">Action</span></th>
                    </tr>
                    <tr class="filter">
                        <th></th>
                        <th>
                            <div class="range">
                                <div class="range-line date">
                                    <!-- <span class="label">From:</span> -->
                                    <input placeholder="From" type="text" name="created_at[from]" id="filter_invoice_created_at_from" value="" class="input-text no-changes" onkeypress="invoiceKeypressDoFilter(event)"/>
                                   
                                </div>
                                <div class="range-line date">
                                    <!-- <span class="label">To:</span> -->
                                    <input placeholder="To" type="text" name="created_at[to]" id="filter_invoice_created_at_to" value="" class="input-text no-changes" onkeypress="invoiceKeypressDoFilter(event)"/>
                                    
                                </div>
                            </div>
                            <script type="text/javascript">
                                require([
                                    "jquery",
                                    "mage/calendar"
                            ], function($,calendar){
                                 $("#filter_invoice_created_at_from").calendar({
                                          dateFormat: "M/d/yy",
                                          showsTime: false,
                                          timeFormat: "HH:mm:ss",
                                          sideBySide: true,
                                          closeText: "Done",
                                          selectOtherMonths: true,
                                          onClose: function( selectedDate ) {
                                            $( "#filter_invoice_created_at_to" ).datepicker( "option", "minDate", selectedDate );
                                          }
                                       });

                                        $("#filter_invoice_created_at_to").calendar({
                                          dateFormat: "M/d/yy",
                                          showsTime: false,
                                          timeFormat: "HH:mm:ss",
                                          sideBySide: true,
                                          closeText: "Done",
                                          selectOtherMonths: true, 
                                          onClose: function( selectedDate ) {
                                            $( "#filter_invoice_created_at_from" ).datepicker( "option", "maxDate", selectedDate );
                                          }
                                       });
                            });
                            </script>
                        </th>
                        <th>
                            <div class="field-100">
                                <input type="text" name="order_number" id="filter_order_number" value="" class="input-text no-changes" onkeypress="invoiceKeypressDoFilter(event)"/>
                            </div>
                        </th>
                        <th>
                            <div class="field-100">
                                <input type="text" name="customer_name" id="filter_customer_name" value="" class="input-text no-changes" onkeypress="invoiceKeypressDoFilter(event)"/>
                            </div>
                        </th>
                        <th></th>
                        <th>
                            <div class="field-100">
                                <input type="text" name="item[item_sku]" id="filter_item_sku" value="" class="input-text no-changes" onkeypress="invoiceKeypressDoFilter(event)"/>
                            </div>
                        </th>
                        <th>
                            <div class="field-100">
                                <input type="text" name="item[item_name]" id="filter_item_name" value="" class="input-text no-changes" onkeypress="invoiceKeypressDoFilter(event)"/>
                            </div>
                        </th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th><div class="actionwidth-100area"></div></th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>

<style>
    #invoicesGrid_table tbody tr td.align-left {
        text-align: left;
    }
    #invoicesGrid_table tbody tr td.align-center {
        text-align: center;
    }
    #invoicesGrid_table tbody tr td.align-right {
        text-align: right;
    }
    #invoicesGrid_table tbody tr td.color-red {
        color: red;
    }
</style>

<script type="text/javascript">
   var $j2='';
    require(['jquery'], function ($) {
         $j2=$;
        $(document).ready(function () {            
            ajaxCall('<?php echo $page ?>', '<?php echo $limit ?>');
        });

        $('#invoiceResetFilter').click(function () {
            invoiceResetFilter();
        });
        $('#invoiceDoFilter').click(function () {
            invoiceDoFilter();
        });
        $('#invoiceUpdate').click(function () {
            invoiceUpdate();
        });
       
    });
    function invoiceSetPage(pageNum, limit) {
        ajaxCall(pageNum, limit);
        $j2("#invoicesGrid table.actions input.input-text.page").val(pageNum);
    }

    function invoiceInputPage(event, limit, totalPage) {
        var element = Event.element(event);
        var keyCode = event.keyCode || event.which;
        var pageNum = 1;
        totalPage = parseInt(totalPage);
        if (keyCode == Event.KEY_RETURN) {
            pageNum = parseInt(element.value);
            if (pageNum < 1) {
                pageNum = 1;
            } else if (pageNum > totalPage) {
                pageNum = totalPage;
            }

            if (isNaN(pageNum)) {
                pageNum = 1;
            }

            ajaxCall(pageNum, limit);
            $j2("#invoicesGrid table.actions input.input-text.page").val(pageNum);
        }
    }

    function invoiceChangeLimit(element) {
        var pageNum = 1;
        var limit = element.value;
        ajaxCall(pageNum, limit);
        $j2("#invoicesGrid table.actions input.input-text.page").val(pageNum);
    }

    function invoiceResetFilter() {
        $j2("input, textarea, select", $j2("#invoicesGrid_table thead tr.filter")).val('');
        ajaxCall('<?php echo $page ?>', '<?php echo $limit ?>');
    }

    function invoiceDoFilter() {
        ajaxCall('<?php echo $page ?>', '<?php echo $limit ?>');
    }

    function invoiceKeypressDoFilter(event) {
        var keyCode = event.keyCode || event.which;
        if (keyCode == Event.KEY_RETURN) {
            ajaxCall('<?php echo $page ?>', '<?php echo $limit ?>');
        }
    }

    function ajaxCall(page, limit) {
         $j2('body').trigger('processStart');
        var filter_var = $j2("input, textarea, select", $j2("#invoicesGrid_table thead tr.filter")).serialize();
        var data = {};
        data.page = page;
        data.limit = limit;
        data.customer_id = '<?php echo $this->getRequest()->getParam('id') ?>';
        data.filter_var = filter_var;
        data.form_key = window.FORM_KEY;
        $j2.ajax({
            url: '<?php echo $this->getUrl("crm/crminvoice/ajaxlist") ?>?isAjax=true',
            type: 'POST', // http method
            data: data, // data to submit
            //data: form_var,  // data to submit
            success: function (data, status, xhr) {
                $j2('body').trigger('processStop');
                var $parsedData = JSON.parse(data);
                $j2('#invoicesGrid_table tbody').html($parsedData.list);
                $j2('#invoicesGrid table.actions tbody tr td.pager').html($parsedData.pagination);
                
            },
            error: function (jqXhr, textStatus, errorMessage) {
                //$('p').append('Error' + errorMessage);
                console.log('Error' + errorMessage);
                $j2('body').trigger('processStop');
            }
        });
    }

    function invoiceUpdate() {
        $j2('body').loader('show');
        var form_var = $j2("input, select", $j2("#invoicesGrid_table tbody")).serialize();
        var data = {};
        data.form_var = form_var;
        data.form_key = window.FORM_KEY;
        $j2.ajax({
            url: '<?php echo $this->getUrl("crm/crminvoice/ajaxupdate") ?>?isAjax=true',
            type: 'POST', // http method
            data: data, // data to submit
            //data: form_var,  // data to submit
            success: function (data, status, xhr) {
                //console.log(data);
                window.location.reload();
            },
            error: function (jqXhr, textStatus, errorMessage) {
                //$('p').append('Error' + errorMessage);
                console.log('Error' + errorMessage);
                window.location.reload();
            }
        });
    }




</script>