<?php $appointment = $block->getAppointmentData(); ?>
<legend>Customer Appointment</legend>
<table id="ajax-form-wrapper">
    <tbody>
        <tr>
            <td>
                <label for="media">Media:</label><br>
                <?php $media = $block->getAppointmentoptionsModel()->getMediaOptions(); ?>
                <select name="appointment[media]" class="select-box">
                    <?php foreach ($media as $_media) { ?>
                        <option value="<?php echo $_media ?>" <?php
                        if ($_media == $appointment['media']) {
                            echo 'selected="selected"';
                        }
                        ?>><?php echo $_media ?></option>
                            <?php } ?>
                </select>
            </td>
            <td>
                <label for="rep">Rep:</label><br>
                <?php $users = $block->getAppointmentoptionsModel()->getAdminUserList(); ?>
                <select name="appointment[rep_user_id]" class="select-box">
                    <?php foreach ($users as $id => $user) { ?>
                        <option value="<?php echo $id ?>" <?php
                        if ($id == $appointment['rep_user_id']) {
                            echo 'selected="selected"';
                        }
                        ?>><?php echo $user ?></option>
                            <?php } ?>
                </select>
            </td>
            <td>
                <label for="contact">Contact:</label><br>
                <input type="text" list="contacts" name="appointment[contact]" class="text-box" value="<?php echo $appointment['contact'] ?>"/>
                <?php $contactList = $block->getContactList(); ?>
                <datalist id="contacts">
                    <?php foreach ($contactList as $_contact) { ?>
                        <option value="<?php echo $_contact ?>">
                        <?php } ?>
                </datalist>
            </td>
        </tr>
        <tr>
            <td colspan="2" class="app-contcttime">
                <label for="contact_time">Contact Time:</label><br>
                <input id="ajax-contact-time-picker" type="text" name="appointment[appointment_time]" class="text-box double" 
                       value="<?php echo $block->getFormattedDate(strtotime($appointment['appointment_time'])) ?>" />
                <!-- <img style="margin: 0 0 0 5px;" title="Select Appointment Time" id="ajax-contact-time-trig" alt="" src="<?php //echo $block->getViewFileUrl("images/grid-cal.gif") ?>"/> -->
            </td>
            <td class="app-status">
                <label for="status">Status:</label><br>
                <?php $status = $block->getAppointmentoptionsModel()->getStatusOptions(); ?>
                <select name="appointment[status]" class="select-box">
                    <?php foreach ($status as $_status) { ?>
                        <option value="<?php echo $_status ?>" <?php
                        if ($_status == $appointment['status']) {
                            echo 'selected="selected"';
                        }
                        ?>><?php echo $_status ?></option>
                            <?php } ?>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                <label for="subject">Subject:</label>
            </td>
            <td colspan="2">
                <input type="text" name="appointment[subject]" class="text-box double" value="<?php echo $appointment['subject'] ?>"/>
            </td>
        </tr>
        <tr>
            <td>
                <label for="note">Notes:</label>
            </td>
            <td colspan="2">
                <textarea name="appointment[note]" class="textarea-box"><?php echo $appointment['note'] ?></textarea>
            </td>
        </tr>
        <tr>
            <td colspan="3" class="ajax-form-buttons">
                <input type="hidden" name="appointment[id]" value="<?php echo $appointment['appointment_id'] ?>"/>
<!--                <input type="button" id="ajax-submit-appointment" value="Save"/>
                <input type="button" id="ajax-cancel-appointment" value="Cancel"/>-->
            </td>
        </tr>
    </tbody>
</table>
<!--<script type="text/javascript">
    Calendar.setup({
        inputField: "ajax-contact-time-picker",
        ifFormat: "%m/%e/%y %H:%M:%S",
        button: "ajax-contact-time-trig",
        showsTime: true,
        align: "Bl",
        singleClick: true
    });
</script>-->

<script>
     require([
          "jquery",
          "mage/calendar"
     ], function($){
         $("#ajax-contact-time-picker").datetimepicker({
              buttonText:"<?php echo __('Select Date') ?>",
              dateFormat: "dd/mm/yy",
            timeFormat: "hh:mm:ss"
         });
       });
</script>